# .github/workflows/release.yml
name: CI/CD Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Publish to npm on push to master
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build (if you have a build step)
        run: npm run build

      - name: Bump version, create Git tag
        run: |
          npm version patch -m "chore(release): %s"

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tags back to GitHub
        run: git push origin --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
